spring:
  mvc:
    async:
      request-timeout: 3600000

server:
  port: 15000

proxy:
  host: 192.168.80.90     # Se ingresa el valor 'non_proxy' (sin comillas) si no se desea configurar proxy 
  port: 3189
  user: mmaccio
password: Lambda01

# Archivo de configuración en cada ambiente
